PMODULES=\
	$GLOBALSCRIPT/src/cmd/gsbc/AssembleFile.pm\

stage1.bcgs: $GLOBALSCRIPT/bin/gsbc $PMODULES bcgs.ags
	gsbc bcgs.ags > $target

stage2.bcgs: $GLOBALSCRIPT/bin/ibio stage1.bcgs bcgs.ags
	$GLOBALSCRIPT/bin/ibio stage1.bcgs bcgs.ags > $target

stage3.bcgs: $GLOBALSCRIPT/bin/ibio stage2.bcgs bcgs.ags
	$GLOBALSCRIPT/bin/ibio stage2.bcgs bcgs.ags > $target

%.listing: %.bcgs
	$GLOBALSCRIPT/bin/ibio -d $stem.bcgs > $target

listing-test: stage2.listing stage3.listing
	diff -c stage2.listing stage3.listing

binaries-test: stage2.bcgs stage3.bcgs
	cmp stage2.bcgs stage3.bcgs

test: listing-test binaries-test
	:
