< $GOARCH.mk

GO=${O}g
GOLD=${O}l

%.$O: %.go
	$GO -o $target $stem.go

$O.%: %.$O
	$GOLD -o $target $stem.$O

$GLOBALSCRIPT/bin/%: $O.%
	cp $O.$stem $target

install: $GLOBALSCRIPT/bin/gsbc

%.bcgs: $O.gsbc %.ags
	$O.gsbc $stem.ags > $target

%.bcgs-test: %.bcgs %.bcgs-expected
	cmp -c $stem.bcgs $stem.gcgs-expected

test: test1.bcgs-test
