< $PLAN9/src/mkhdr

SYSTEM=unix
CFLAGS=-I $SYSTEM

OFILES=\
	$SYSTEM/iodir.$O \
	iostat.$O \
	iochan.$O \

LIB=libibio.a

$GLOBALSCRIPT/lib/$LIB(%):N: %
$GLOBALSCRIPT/lib/$LIB:	${OFILES:%=$GLOBALSCRIPT/lib/$LIB(%)}
	$AR rsc $GLOBALSCRIPT/lib/$LIB $newmember

&:n:	&.$O
	$AR rsc $GLOBALSCRIPT/lib/$LIB $stem.$O

iochan.$O: iofile.h $SYSTEM/iosysconstants.h
iostat.$O: iostat.h
unix/iodir.$O: iofile.h iostat.h

%.$O: $GLOBALSCRIPT/include/libglobalscript.h $GLOBALSCRIPT/include/libibio.h

all install:V: $GLOBALSCRIPT/lib/$LIB

NUKEFILES=$NUKEFILES $GLOBALSCRIPT/lib/$LIB

%.$O:	%.c
	$CC $CFLAGS -o $target $stem.c

< $GLOBALSCRIPT/src/mkcommon
