< $PLAN9/src/mkhdr

SYSTEM=unix
CFLAGS=-I $SYSTEM -g
LDFLAGS=-g

OFILES=\
	$SYSTEM/iodir.$O \
	$SYSTEM/iosysconstants.$O \
	iochan.$O \
	iostat.$O \

TEST_OFILES=\
	test.$O \
	$SYSTEM/test.$O \
	test_iostat.$O \
	$SYSTEM/test_iodir.$O \
	test_iochan.$O \

LIB=libibio.a

$GLOBALSCRIPT/lib/$LIB(%):N: %
$GLOBALSCRIPT/lib/$LIB:	${OFILES:%=$GLOBALSCRIPT/lib/$LIB(%)}
	$AR rsc $GLOBALSCRIPT/lib/$LIB $newmember

&:n:	&.$O
	$AR rsc $GLOBALSCRIPT/lib/$LIB $stem.$O

iochan.$O: iofile.h $SYSTEM/iosysconstants.h iomacros.h
iostat.$O: $SYSTEM/iosysconstants.h iofile.h iostat.h iomacros.h
unix/iodir.$O: iofile.h iostat.h iomacros.h unix/iodir.h

%.$O: $GLOBALSCRIPT/include/libglobalscript.h $GLOBALSCRIPT/include/libibio.h

all install:V: test $GLOBALSCRIPT/lib/$LIB

test:V: $O.test
    ./$O.test

$O.test:	$TEST_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libtest.a
	$LD -o $target $prereq $LDFLAGS

test.$O:	$GLOBALSCRIPT/include/libtest.h test_tests.h $SYSTEM/test_systemtests.h
test_iostat.$O:	$GLOBALSCRIPT/include/libtest.h $SYSTEM/iosysconstants.h iofile.h iostat.h iomacros.h test_tests.h
unix/test_iodir.$O:	$GLOBALSCRIPT/include/libtest.h unix/iosysconstants.h iofile.h iomacros.h unix/iodir.h unix/test_systemtests.h

NUKEFILES=$NUKEFILES $TEST_OFILES $GLOBALSCRIPT/lib/$LIB

%.$O:	%.c
	$CC $CFLAGS -o $target $stem.c

< $GLOBALSCRIPT/src/mkcommon
