< $GLOBALSCRIPT/src/mkhdr

MKSHELL=$PLAN9/bin/rc

LOCAL_TARGETS=\
	./gscr.gsac \
	./gscr-targets.gsac \
	./gscr-deps.gsac \
	`{$GLOBALSCRIPT/bin/gsac-targets ./gslib} \

interpreted:V: $LOCAL_TARGETS
	true

< $GLOBALSCRIPT/src/mkcommon
