< $PLAN9/src/mkhdr

< $GLOBALSCRIPT/src/mkhdr

all:V: pure-all

pure-all:V: $O.gstype $O.gstest $O.gslint

pure-install:V: $GLOBALSCRIPT/bin/gstype $GLOBALSCRIPT/bin/gstest $GLOBALSCRIPT/bin/gslint

pure-integration-test:V: rc/pure-test $O.gstype $O.gstest $O.gslint
	./rc/pure-test

$GLOBALSCRIPT/bin/%: $O.%
	cp $prereq $target

$O.%: %.$O $GLOBALSCRIPT/lib/libglobalscript.a
	$LD $LDFLAGS -o $target $stem.$O -lglobalscript

%.$O: %.c
	$CC $CFLAGS -o $target $stem.c

%.$O: $GLOBALSCRIPT/include/libglobalscript.h

hello:V:
	echo Hello, world
