< $GLOBALSCRIPT/src/mkhdr

MKSHELL=$PLAN9/bin/rc

GSLIB_TARGETS=`{$PLAN9/bin/rc ./gslib-targets}

<| $PLAN9/bin/rc ./gslib-deps -l $GLOBALSCRIPT/gslib $GSLIB_TARGETS

interpreted:V:
	true

integration-test-interpreted:V: interpreted
	./rc/test-interpreted

install-interpreted:V: interpreted
	cp gsac.rc $GLOBALSCRIPT/bin/gsac
	chmod a+x $GLOBALSCRIPT/bin/gsac
	cp gsac-targets.rc $GLOBALSCRIPT/bin/gsac-targets
	chmod a+x $GLOBALSCRIPT/bin/gsac-targets
	cp gsac-deps.rc $GLOBALSCRIPT/bin/gsac-deps
	chmod a+x $GLOBALSCRIPT/bin/gsac-deps

effect:V: $GSLIB_TARGETS
	true
