< $GLOBALSCRIPT/src/mkhdr

MKSHELL=$PLAN9/bin/rc

GSLIB_TARGETS=`{$PLAN9/bin/rc ./gslib-targets}

<| $PLAN9/bin/rc ./gslib-deps

interpreted:V:
	true

install-interpreted:V: interpreted
	cp gsac.rc $GLOBALSCRIPT/bin/gsac
	chmod a+x $GLOBALSCRIPT/bin/gsac
	cp gsac-targets.rc $GLOBALSCRIPT/bin/gsac-targets
	chmod a+x $GLOBALSCRIPT/bin/gsac-targets

effect:V: $GSLIB_TARGETS
	true
