< $PLAN9/src/mkhdr

SYSTEM=unix

< $SYSTEM/mkhdr

OFILES=\
	gsmain.$O \
	gsfatal.$O \
	apithread.$O \
	eval.$O \
	load.$O \
	inputalloc.$O \
	alloc.$O \
	eval.$O \
	ace.$O \
	symtable.$O \
	bytecompile.$O \
	primset.$O \
	typealloc.$O \
	typecheck.$O \
	clienttypecheck.$O \
	clientexpr.$O \
	bctopsort.$O \
	gsrpc.$O \
	regtables.$O \
	runes.$O \
	$SYSTEM/lock.$O \
	$SYSTEM/$CPU/tas.$O \
	$SYSTEM/gssysthreads.$O \

TEST_OFILES=\
	test.$O \
	test_macros.$O \
	test_load.$O \
	test_symtable.$O \
	test_typealloc.$O \

TEST_GSI_OFILES=\
	test-gsi.$O \

TEST_GSEXEC_OFILES=\
	test-gsexec.$O \

LIB=libglobalscript.a

$GLOBALSCRIPT/lib/$LIB(%):N: %
$GLOBALSCRIPT/lib/$LIB:	${OFILES:%=$GLOBALSCRIPT/lib/$LIB(%)}
	$AR rsc $GLOBALSCRIPT/lib/$LIB $newmember

&:n:	&.$O
	$AR rsc $GLOBALSCRIPT/lib/$LIB $stem.$O

%.$O: $GLOBALSCRIPT/include/libglobalscript.h
gsmain.$O: gsinputfile.h gssetup.h gsregtables.h ace.h
load.$O: gsinputalloc.h gsinputfile.h $GLOBALSCRIPT/include/libibio.h gsbytecompile.h gsregtables.h gstopsort.h gstypealloc.h gstypecheck.h ace.h
inputalloc.$O: gsinputfile.h gsinputalloc.h
alloc.$O: gsalloc.h
eval.$O: gsheap.h gsinputfile.h gsregtables.h ace.h
ace.$O: gsheap.h gsregtables.h ace.h
apithread.$O: gsregtables.h gsheap.h api.h
symtable.$O: gsinputfile.h
bytecompile.$O: $GLOBALSCRIPT/include/libibio.h gsinputfile.h gsregtables.h gstypealloc.h gsbytecompile.h gsheap.h gstopsort.h gstypealloc.h
primset.$O: gsinputfile.h gssetup.h
typealloc.$O: gsinputfile.h gsregtables.h gstypealloc.h gstypecheck.h
typecheck.$O: gsinputfile.h gsregtables.h gstypealloc.h gstypecheck.h
clienttypecheck.$O: gsinputfile.h gstypealloc.h gstypecheck.h
clientexpr.$O: gsinputfile.h gstypealloc.h gstypecheck.h
bctopsort.$O: gsinputfile.h gstopsort.h
regtables.$O: gsinputfile.h gsregtables.h
api.$O: api.h

all install:V: test $GLOBALSCRIPT/lib/$LIB

test:V: $O.test
    ./$O.test

integration-test:V: test test-rc

test-rc:V: rc/test $O.test-gsi $O.test-gsexec
    ./rc/test

$O.test:	$TEST_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libtest.a $GLOBALSCRIPT/lib/libibio.a
	$LD -o $target $prereq $LDFLAGS

test.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h
test_macros.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h
test_symtable.$O: $GLOBALSCRIPT/include/libtest.h gsinputfile.h test_tests.h
test_load.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h
test_typealloc.$O: $GLOBALSCRIPT/include/libtest.h gsinputfile.h gstypealloc.h test_tests.h

test-gsi.$O: gsinputfile.h gstypealloc.h

$O.test-gsi:	$TEST_GSI_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libibio.a
	$LD -o $target $prereq $LDFLAGS

%.$O:	%.c
	$CC $CFLAGS -o $target $stem.c

%.$O:	%.s
	$AS $ASFLAGS $stem.s

$O.test-gsexec:	$TEST_GSEXEC_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libibio.a
	$LD -o $target $prereq $LDFLAGS

NUKEFILES=$NUKEFILES $TEST_OFILES $GLOBALSCRIPT/lib/$LIB

< $GLOBALSCRIPT/src/mkcommon
