< $PLAN9/src/mkhdr

OFILES=\
	gsmain.$O \
	gsfatal.$O \
	apithread.$O \
	eval.$O \
	load.$O \
	inputalloc.$O \
	alloc.$O \
	eval.$O \
	ace.$O \
	symtable.$O \
	bytecompile.$O \
	primset.$O \
	typealloc.$O \
	typecheck.$O \
	bctopsort.$O \

TEST_OFILES=\
	test.$O \
	test_macros.$O \
	test_load.$O \
	test_symtable.$O \

TEST_GSI_OFILES=\
	test-gsi.$O \

LIB=libglobalscript.a

$GLOBALSCRIPT/lib/$LIB(%):N: %
$GLOBALSCRIPT/lib/$LIB:	${OFILES:%=$GLOBALSCRIPT/lib/$LIB(%)}
	$AR rsc $GLOBALSCRIPT/lib/$LIB $newmember

&:n:	&.$O
	$AR rsc $GLOBALSCRIPT/lib/$LIB $stem.$O

%.$O: $GLOBALSCRIPT/include/libglobalscript.h
gsmain.$O: gsinputfile.h gssetup.h ace.h
load.$O: gsinputalloc.h gsinputfile.h $GLOBALSCRIPT/include/libibio.h gsbytecompile.h gstopsort.h gstypealloc.h gstypecheck.h
inputalloc.$O: gsinputfile.h gsinputalloc.h
alloc.$O: gsalloc.h
eval.$O: gsheap.h
symtable.$O: gsinputfile.h
bytecompile.$O: $GLOBALSCRIPT/include/libibio.h gsinputfile.h gsbytecompile.h gsheap.h gstopsort.h gstypealloc.h
primset.$O: gsinputfile.h gssetup.h
typealloc.$O: gsinputfile.h gstypealloc.h
typecheck.$O: gsinputfile.h gstypealloc.h gstypecheck.h
bctopsort.$O: gsinputfile.h gstopsort.h

all install:V: test $GLOBALSCRIPT/lib/$LIB

test:V: $O.test
    ./$O.test

integration-test:V: test test-rc

test-rc:V: rc/test $O.test-gsi
    ./rc/test

$O.test:	$TEST_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libtest.a
	$LD -o $target $prereq $LDFLAGS

test.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h
test_macros.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h
test_symtable.$O: $GLOBALSCRIPT/include/libtest.h gsinputfile.h test_tests.h
test_load.$O: $GLOBALSCRIPT/include/libtest.h test_tests.h

$O.test-gsi:	$TEST_GSI_OFILES $GLOBALSCRIPT/lib/$LIB $GLOBALSCRIPT/lib/libibio.a
	$LD -o $target $prereq $LDFLAGS

NUKEFILES=$NUKEFILES $TEST_OFILES $GLOBALSCRIPT/lib/$LIB

< $PLAN9/src/mkcommon
< $GLOBALSCRIPT/src/mkcommon
