< $PLAN9/src/mkhdr

OFILES=

TARG=iotest

< $PLAN9/src/mkone
< $GLOBALSCRIPT/src/mkcommon

$PROG: $GLOBALSCRIPT/lib/libglobalscript.a

test:VN: test-unit.iotest.gs

test-%.iotest.gs: %.iotest.gs $PROG $GLOBALSCRIPT/bin/gsbc `{echo $GLOBALSCRIPT/src/cmd/gsbc/*.pm} %.ibio.ags
	./$PROG $stem.iotest.gs
