/* AUTOMATICALLY GENERATED BY APITHREADCOMPILE
   DO NOT EDIT OR BEARS WILL EAT YOU */

#include <u.h>
#include <libc.h>
#include <libglobalscript.h>
#include "ibio.h"



void
ibiothreadmain(apithreadqueue *q)
{
    while(1) {
        /* qlock(q->lock); */
        gstypecode tc = gs_get_gsvalue_state(q->curthread->pc->instr);
        switch (tc) {
            default:
                gsfatal("Unknown typecode; numeric value %x\n", tc);
        }
        /* qunlock(q->lock); */
    }
}
