< $PLAN9/src/mkhdr

OFILES=\
	ibio.$O \

TARG=ibio

< $PLAN9/src/mkone
< $GLOBALSCRIPT/src/mkcommon

$PROG: $GLOBALSCRIPT/lib/libglobalscript.a $GLOBALSCRIPT/lib/libibio.a

all install:V: test

%.$O: $GLOBALSCRIPT/include/libglobalscript.h
ibio.$O: ibio.h

test:V: 
    :

integration-test:V: test test-rc

test-rc:V: rc/test $O.ibio
    ./rc/test

%.ibio.ags-out: $PROG $GLOBALSCRIPT/bin/gsbc `{echo $GLOBALSCRIPT/src/cmd/gsbc/*.pm} %.ibio.ags
	./$PROG $stem.ibio.ags > $stem.ibio.ags-out

%.ibio.listing: %.ibio.bcgs
	od -Ax -c $stem.ibio.bcgs > $stem.ibio.listing

clean:VN:
	rm -f ibiothreadmain.c
	rm -f *.$O
